### ISSUE TITLE
Call to undefined method Kirby\Cms\App::model()

### ISSUE THREAD

**Issue by nilshoerrmann** [medienbaecker/kirby-cropselect#2]
When giving this plugin a try today, I got this error message in the panel:

![bildschirmfoto am 2018-10-18 um 09 57 06](https://user-images.githubusercontent.com/25466/47139516-464df980-d2bc-11e8-8b57-ab4027c3421e.png)

**Comment by medienbaecker** [comment]
I finally got this fixed. For anybody else suddenly having an erroneous plugin:

If you want to access something like `$this->model()->type()` do it in the `computed` part, not in the regular `props`. [The commit](https://github.com/medienbaecker/kirby-cropselect/commit/302ea3ab9c71f4f83c8d52483e632fda3d7127da).
